<?php
/**
 * Copyright (c) 2020 Heimrich & Hannot GmbH
 *
 * @license LGPL-3.0-or-later
 */

namespace HeimrichHannot\EntityImportBundle\Importer;


class FileCSVImporter extends FileImporter
{

    public function getData()
    {
        // TODO: Implement getData() method.
    }

    public function run($dry = false)
    {
        parent::run($dry); // TODO: Change the autogenerated stub
    }
}