services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  HeimrichHannot\EntityImportBundle\:
    resource: ../src
    exclude: ../src/{ContaoManager,DependencyInjection,HeimrichHannotContaoEntityImportBundle.php}
