<?php

/*
 * Copyright (c) 2021 Heimrich & Hannot GmbH
 *
 * @license LGPL-3.0-or-later
 */

namespace HeimrichHannot\EntityImportBundle;

use Symfony\Component\HttpKernel\Bundle\AbstractBundle;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class HeimrichHannotContaoEntityImportBundle extends Bundle
{
    public function getPath(): string
    {
        return \dirname(__DIR__);
    }
    protected function getContainerExtensionClass(): string
    {
        return parent::getContainerExtensionClass(); // TODO: Change the autogenerated stub
    }
}
